/**
 * Large diverse incident dataset for CargoWatch demo
 * Includes varied locations, times, severities, and types
 */

export function generateIncidentData(demoUsers: any[]) {
  const now = Date.now();

  return [
    // Critical - Recent (last 6 hours)
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "theft",
      severityLevel: "critical",
      cargoType: "electronics",
      status: "active",
      region: "Los Angeles, CA",
      specificLocation: "I-5 Pilot Travel Center, Exit 12",
      latitude: "34.0234", longitude: "-118.2567",
      title: "Multiple Vehicles Circling Truck Stop",
      description: "Observed 3 unmarked vehicles circling the parking lot at the Pilot Travel Center on I-5. Vehicles appeared to be surveying parked trailers. Suspicious behavior noted around pharmaceuticals trailer. Drivers should exercise extreme caution in this area.",
      incidentDate: new Date(now - 2 * 60 * 60 * 1000),
      incidentTime: "23:45",
      hasPhotos: true, hasVideo: true, evidenceCount: 3,
      estimatedLoss: "0.00",
      viewCount: 347, commentCount: 12, shareCount: 45,
      reporterName: "Swift Transport Driver", reporterCompany: "Swift Transportation",
    },
    {
      reporterId: demoUsers[1]!.id,
      incidentType: "theft",
      severityLevel: "critical",
      cargoType: "electronics",
      status: "active",
      region: "Newark, NJ",
      specificLocation: "Commerce Distribution Center",
      latitude: "40.7425", longitude: "-74.1683",
      title: "Cargo Theft - Electronics Load Stolen",
      description: "Full trailer of consumer electronics stolen from secured yard facility overnight. Gate lock was cut, security cameras were painted. Estimated value $850,000. Trailer ID: TRL-8847303. Local PD #2024-11647 filed. Be vigilant in surrounding areas.",
      incidentDate: new Date(now - 4 * 60 * 60 * 1000),
      incidentTime: "03:15",
      hasPhotos: true, hasVideo: false, evidenceCount: 4,
      estimatedLoss: "850000.00",
      viewCount: 589, commentCount: 28, shareCount: 67,
      reporterName: "Warehouse Security", reporterCompany: "XPO Logistics",
    },
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "tampering",
      severityLevel: "high",
      cargoType: "pharmaceuticals",
      status: "investigating",
      region: "Atlanta, GA",
      specificLocation: "Lane's Transit Stop, I-20 South",
      latitude: "33.7632", longitude: "-84.4219",
      title: "Seal Tampering Detected",
      description: "Driver discovered container seal had been cut and replaced with counterfeit during overnight stop. Cargo appears intact but full inventory check required. Recommend increased vigilance before departing rest stops.",
      incidentDate: new Date(now - 5 * 60 * 60 * 1000),
      incidentTime: "06:30",
      hasPhotos: true, hasVideo: false, evidenceCount: 2,
      estimatedLoss: "0.00",
      viewCount: 234, commentCount: 15, shareCount: 32,
      reporterName: "Independent O/O", reporterCompany: "JB Hunt Transport",
    },

    // High Priority - Last 24 hours
    {
      reporterId: demoUsers[2]!.id,
      incidentType: "suspicious",
      severityLevel: "high",
      cargoType: "general",
      status: "active",
      region: "Chicago, IL",
      specificLocation: "Industrial Boulevard Corridor",
      latitude: "41.8543", longitude: "-87.6712",
      title: "Suspicious Individuals Approaching Drivers",
      description: "Two men approached drivers at fuel island asking detailed questions about cargo and routes. Alert divers refused to engage. Description: Male, 30s, dark clothing. Alert other drivers.",
      incidentDate: new Date(now - 8 * 60 * 60 * 1000),
      incidentTime: "14:30",
      hasPhotos: false, hasVideo: false, evidenceCount: 0,
      estimatedLoss: "0.00",
      viewCount: 178, commentCount: 8, shareCount: 23,
      reporterName: "Facility Security", reporterCompany: "Jill Haul Ind O/O",
    },
    {
      reporterId: demoUsers[1]!.id,
      incidentType: "attempted_break_in",
      severityLevel: "high",
      cargoType: "food",
      status: "active",
      region: "Memphis, TN",
      specificLocation: "FedEx Staging Facility North",
      latitude: "35.2187", longitude: "-90.0372",
      title: "Attempted Break-in at Staging Area",
      description: "Caught two suspects attempting to break kingpin lock on pharmaceutical trailer at 3:45 AM. Suspects fled in dark colored sedan. Security footage captured and shared with MPD.",
      incidentDate: new Date(now - 12 * 60 * 60 * 1000),
      incidentTime: "03:45",
      hasPhotos: true, hasVideo: true, evidenceCount: 4,
      estimatedLoss: "0.00",
      viewCount: 412, commentCount: 22, shareCount: 58,
      reporterName: "Facility Security", reporterCompany: "Independent O/O",
    },
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "theft",
      severityLevel: "critical",
      cargoType: "pharmaceuticals",
      status: "investigating",
      region: "Dallas, TX",
      specificLocation: "Highway 51 Near Millington",
      latitude: "32.8123", longitude: "-96.7891",
      title: "GPS Jammer Detected in Area",
      description: "Multiple carriers reporting GPS signal loss in concentrated area near warehouse district. Possible GPS jamming device in operation. Tracking systems intermittently failing. Law enforcement notified.",
      incidentDate: new Date(now - 15 * 60 * 60 * 1000),
      incidentTime: "21:00",
      hasPhotos: false, hasVideo: false, evidenceCount: 0,
      estimatedLoss: "0.00",
      viewCount: 567, commentCount: 33, shareCount: 87,
      reporterName: "Fleet Manager", reporterCompany: "ABC Logistics",
    },

    // Medium Priority - Last 2 days
    {
      reporterId: demoUsers[2]!.id,
      incidentType: "suspicious",
      severityLevel: "medium",
      cargoType: "electronics",
      status: "active",
      region: "Houston, TX",
      specificLocation: "Port of Houston Container Facility",
      latitude: "29.7321", longitude: "-95.2876",
      title: "Suspicious Vehicle Circling Facility",
      description: "White van with surveillance equipment observed circling container facility yesterday. Occupants photographing truck movements and gate schedules. License partially visible: TX 8**-D1R. Report any similar sightings.",
      incidentDate: new Date(now - 28 * 60 * 60 * 1000),
      incidentTime: "14:30",
      hasPhotos: true, hasVideo: false, evidenceCount: 2,
      estimatedLoss: "0.00",
      viewCount: 156, commentCount: 7, shareCount: 14,
      reporterName: "Port Security", reporterCompany: "Tennessee State Police",
    },
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "tampering",
      severityLevel: "medium",
      cargoType: "food",
      status: "resolved",
      region: "Phoenix, AZ",
      specificLocation: "Loves Travel Stop, I-35 South",
      latitude: "33.4892", longitude: "-112.1127",
      title: "Recovered Stolen Food Shipment",
      description: "Thanks to community alert, semi-trailer containing $200K in frozen food products was recovered 45 miles from theft location. Suspects apprehended. Great example of community cooperation.",
      incidentDate: new Date(now - 32 * 60 * 60 * 1000),
      incidentTime: "18:45",
      hasPhotos: true, hasVideo: false, evidenceCount: 3,
      estimatedLoss: "200000.00",
      viewCount: 289, commentCount: 19, shareCount: 41,
      reporterName: "Law Enforcement", reporterCompany: "Tennessee State Police",
    },
    {
      reporterId: demoUsers[1]!.id,
      incidentType: "suspicious",
      severityLevel: "medium",
      cargoType: "general",
      status: "active",
      region: "Miami, FL",
      specificLocation: "TA Truck Stop, Exit 12",
      latitude: "25.7834", longitude: "-80.2156",
      title: "Drone Activity Over Secure Lot",
      description: "Security personnel observed drone flying over secure container yard for approximately 20 minutes. Drone appeared to be surveying high-value cargo areas. Unable to locate operator. Recommend increased vigilance.",
      incidentDate: new Date(now - 40 * 60 * 60 * 1000),
      incidentTime: "22:15",
      hasPhotos: false, hasVideo: true, evidenceCount: 1,
      estimatedLoss: "0.00",
      viewCount: 198, commentCount: 11, shareCount: 19,
      reporterName: "Port Security", reporterCompany: "Long Beach Container Facility",
    },
    {
      reporterId: demoUsers[2]!.id,
      incidentType: "attempted_break_in",
      severityLevel: "high",
      cargoType: "electronics",
      status: "active",
      region: "Seattle, WA",
      specificLocation: "Walmart Distribution Center",
      latitude: "47.6234", longitude: "-122.3512",
      title: "Attempted Break-in at Staging Area",
      description: "Driver discovered bolt cutters and lock picking tools next to trailer this morning. Security lock shows tampering marks but held. Electronics shipment secure. Incident between 3-5 AM.",
      incidentDate: new Date(now - 48 * 60 * 60 * 1000),
      incidentTime: "04:00",
      hasPhotos: true, hasVideo: false, evidenceCount: 4,
      estimatedLoss: "0.00",
      viewCount: 223, commentCount: 14, shareCount: 27,
      reporterName: "Swift Transport Driver", reporterCompany: "Lancaster Distribution",
    },

    // Various Times and Locations - Last Week
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "theft",
      severityLevel: "critical",
      cargoType: "pharmaceuticals",
      status: "investigating",
      region: "Baltimore, MD",
      specificLocation: "I-40 Pilot Travel Center",
      latitude: "39.3142", longitude: "-76.6387",
      title: "Cargo Theft - Prescription Drugs",
      description: "Entire pharmaceutical shipment stolen during mandatory rest break. GPS jammer suspected as tracking went offline. Load valued at $1.8M, contains controlled substances. FBI notified.",
      incidentDate: new Date(now - 72 * 60 * 60 * 1000),
      incidentTime: "23:30",
      hasPhotos: false, hasVideo: false, evidenceCount: 0,
      estimatedLoss: "1800000.00",
      viewCount: 678, commentCount: 41, shareCount: 93,
      reporterName: "Warehouse Security", reporterCompany: "Southwest Freight",
    },
    {
      reporterId: demoUsers[1]!.id,
      incidentType: "suspicious",
      severityLevel: "medium",
      cargoType: "general",
      status: "active",
      region: "Denver, CO",
      specificLocation: "Interstate Boulevard Corridor",
      latitude: "39.7521", longitude: "-105.0103",
      title: "Suspicious Individuals Approaching Drivers",
      description: "Two individuals on foot approaching drivers at rest areas, asking detailed questions about cargo contents and delivery schedules. When questioned, subjects quickly left area. Both male, mid-30s.",
      incidentDate: new Date(now - 84 * 60 * 60 * 1000),
      incidentTime: "02:15",
      hasPhotos: false, hasVideo: false, evidenceCount: 0,
      estimatedLoss: "0.00",
      viewCount: 167, commentCount: 9, shareCount: 15,
      reporterName: "Independent O/O", reporterCompany: "Facility Security",
    },
    {
      reporterId: demoUsers[2]!.id,
      incidentType: "tampering",
      severityLevel: "high",
      cargoType: "food",
      status: "active",
      region: "Philadelphia, PA",
      specificLocation: "Love's Travel Stop, I-35E Mile 428",
      latitude: "39.9712", longitude: "-75.1891",
      title: "Seal Tampering Detected",
      description: "Discovered trailer seal was broken during pre-trip inspection. Seal #: 45782-B. Refrigerated food products. No visible cargo missing but entire shipment may be compromised.",
      incidentDate: new Date(now - 96 * 60 * 60 * 1000),
      incidentTime: "06:45",
      hasPhotos: true, hasVideo: false, evidenceCount: 2,
      estimatedLoss: "45000.00",
      viewCount: 234, commentCount: 13, shareCount: 22,
      reporterName: "Swift Transport Driver", reporterCompany: "J.B. Hunt Transport",
    },
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "theft",
      severityLevel: "critical",
      cargoType: "electronics",
      status: "active",
      region: "Oakland, CA",
      specificLocation: "Port of Oakland, Pier J",
      latitude: "37.8127", longitude: "-122.2891",
      title: "Trailer Theft - Electronics Cargo",
      description: "Full trailer stolen from secured port facility. Load contained high-value electronics valued at $2.3M. Professional operation with security system bypass. Local PD investigating.",
      incidentDate: new Date(now - 108 * 60 * 60 * 1000),
      incidentTime: "01:30",
      hasPhotos: true, hasVideo: true, evidenceCount: 5,
      estimatedLoss: "2300000.00",
      viewCount: 892, commentCount: 52, shareCount: 134,
      reporterName: "Facility Security", reporterCompany: "XPO Logistics",
    },
    {
      reporterId: demoUsers[1]!.id,
      incidentType: "suspicious",
      severityLevel: "low",
      cargoType: "general",
      status: "resolved",
      region: "San Antonio, TX",
      specificLocation: "Walmart Distribution Center",
      latitude: "29.4512", longitude: "-98.5234",
      title: "Suspicious Vehicle Circling Facility",
      description: "White van circled distribution center multiple times. License plate captured and provided to local PD. Vehicle was stolen, suspects apprehended. Case closed.",
      incidentDate: new Date(now - 120 * 60 * 60 * 1000),
      incidentTime: "14:30",
      hasPhotos: true, hasVideo: true, evidenceCount: 6,
      estimatedLoss: "0.00",
      viewCount: 145, commentCount: 7, shareCount: 11,
      reporterName: "Fleet Manager", reporterCompany: "Independent O/O",
    },

    // Additional diverse incidents across more locations
    {
      reporterId: demoUsers[2]!.id,
      incidentType: "attempted_break_in",
      severityLevel: "medium",
      cargoType: "pharmaceuticals",
      status: "active",
      region: "Columbus, OH",
      specificLocation: "TA Truck Stop, I-40 Exit 25",
      latitude: "39.9784", longitude: "-83.0145",
      title: "Attempted Break-in - Bolt Cutters Found",
      description: "Found bolt cutters and pry bar next to trailer door. Locks show signs of tampering but held. Pharmaceutical load. Incident occurred between 2-4 AM per security camera review.",
      incidentDate: new Date(now - 132 * 60 * 60 * 1000),
      incidentTime: "04:00",
      hasPhotos: true, hasVideo: true, evidenceCount: 3,
      estimatedLoss: "0.00",
      viewCount: 189, commentCount: 11, shareCount: 18,
      reporterName: "Warehouse Security", reporterCompany: "Swift Transportation",
    },
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "theft",
      severityLevel: "high",
      cargoType: "electronics",
      status: "investigating",
      region: "Laredo, TX",
      specificLocation: "I-710 Rest Area, Northbound",
      latitude: "27.5487", longitude: "-99.4976",
      title: "Cross-Border Cargo Theft",
      description: "Electronics shipment stolen near border crossing. Professional operation targeting cross-border freight. CBP and FBI investigating. Value $680K.",
      incidentDate: new Date(now - 144 * 60 * 60 * 1000),
      incidentTime: "21:00",
      hasPhotos: false, hasVideo: false, evidenceCount: 0,
      estimatedLoss: "680000.00",
      viewCount: 534, commentCount: 29, shareCount: 61,
      reporterName: "Law Enforcement", reporterCompany: "XPO Logistics",
    },
    {
      reporterId: demoUsers[1]!.id,
      incidentType: "suspicious",
      severityLevel: "medium",
      cargoType: "general",
      status: "active",
      region: "El Paso, TX",
      specificLocation: "Border Staging Area",
      latitude: "31.7891", longitude: "-106.5012",
      title: "Suspicious Activity Near Border Crossing",
      description: "Multiple reports of unmarked vehicles following trucks from border crossing. Vehicles appear coordinated. Border Patrol alerted.",
      incidentDate: new Date(now - 156 * 60 * 60 * 1000),
      incidentTime: "16:45",
      hasPhotos: false, hasVideo: false, evidenceCount: 0,
      estimatedLoss: "0.00",
      viewCount: 267, commentCount: 16, shareCount: 28,
      reporterName: "Independent O/O", reporterCompany: "J.B. Hunt Transport",
    },
    {
      reporterId: demoUsers[2]!.id,
      incidentType: "tampering",
      severityLevel: "low",
      cargoType: "food",
      status: "resolved",
      region: "Long Beach, CA",
      specificLocation: "Port Container Yard",
      latitude: "33.7812", longitude: "-118.2078",
      title: "Minor Seal Damage Detected",
      description: "Container seal showed minor damage during inspection. Full inventory check confirmed no cargo missing. Likely accidental damage during handling. Incident logged for records.",
      incidentDate: new Date(now - 168 * 60 * 60 * 1000),
      incidentTime: "10:15",
      hasPhotos: true, hasVideo: false, evidenceCount: 1,
      estimatedLoss: "0.00",
      viewCount: 98, commentCount: 3, shareCount: 5,
      reporterName: "Port Security", reporterCompany: "Independent O/O",
    },
    {
      reporterId: demoUsers[0]!.id,
      incidentType: "theft",
      severityLevel: "critical",
      cargoType: "pharmaceuticals",
      status: "active",
      region: "Kansas City, MO",
      specificLocation: "Distribution Hub",
      latitude: "39.1234", longitude: "-94.6012",
      title: "High-Value Pharma Theft",
      description: "Organized theft of high-value pharmaceutical shipment. Multiple suspects, professional operation. GPS disabled. FBI investigating as part of larger organized crime case. $1.2M value.",
      incidentDate: new Date(now - 180 * 60 * 60 * 1000),
      incidentTime: "03:20",
      hasPhotos: false, hasVideo: false, evidenceCount: 0,
      estimatedLoss: "1200000.00",
      viewCount: 723, commentCount: 38, shareCount: 98,
      reporterName: "Fleet Manager", reporterCompany: "Swift Transportation",
    },
  ];
}
